### ISSUE TITLE
How to Trigger the Indexer Programmatically with UPT

### ISSUE THREAD

**Issue by amikoreh** [FacetWP/user-post-type#2]
I'm trying to get FacetWP and UPT to re-index/sync after new WP user is registered. I know for FacetWP you can [trigger an index](https://facetwp.com/how-to-trigger-the-indexer-programmatically/) using `FWP()->indexer->index();`. Is there a way to trigger the UPT to sync (copy extra data into postmeta) programmatically?

I looked through the UPT code and I was thinking this should work, but I'm not sure it is: `UPT()->sync->run_sync();`

Here is my code:
```
add_action( 'user_register', 'custom_user_register', 10, 2 );
function custom_user_register( $user_id, $args ) {
    UPT()->sync->run_sync();
    FWP()->indexer->index();
}
```
Thanks for your help!

**Comment by mgibbs189** [comment]
@amikoreh Yes that's the right code, although UPT does already sync automatically on the `user_register` hook.
